<?php

/**
  * Implementation of hook_form_alter.
  * Unset menu node translation
  */
function sigrids_stue_admin_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] .'_node_form' == $form_id) {
    unset($form['menu']['i18nmenu_node_translation']);
  }
}

/**
  * Implementation of hook_form_comment_form_alter().
  * Change button value and remove preview button.
  */
function sigrids_stue_admin_form_comment_form_alter(&$form, &$form_state) {
    // Change value of submit button.
    $form['submit']['#value'] = t('Add comment');
    
    // Remove preview button.
    unset($form['preview']);
}